csv_header = [
    "Nome de usuário",
    "ID",
    "AvatarURL",
    "GravatarID",
    "URL",
    "HTMLURL",
    "FollowersURL",
    "FollowingURL",
    "GistsURL",
    "StarredURL",
    "SubscriptionsURL",
    "OrganizationsURL",
    "ReposURL",
    "EventsURL",
    "ReceivedEventsURL",
    "Type",
    "SiteAdmin",
    "Name",
    "Company",
    "Blog",
    "Location",
    "Email",
    "Hireable",
    "Bio",
    "PublicRepos",
    "PublicGists",
    "Followers",
    "Following",
    "CreatedAt",
    "UpdatedAt",
    "Following Users",
    "Followers Users",
]
