initial_data_path = "/home/luciano/Documentos/Github/complex-networks/resources/data/initial_users_data.csv" 
base_initial_data_path = "/home/luciano/Documentos/Github/complex-networks/resources/data/initial_users_data_" 
base_path_random_data = "/home/luciano/Documentos/Github/complex-networks/resources/data/random_users_data_"
graph_random_users = "/home/luciano/Documentos/Github/complex-networks/resources/data/graph_randon_users_50.csv"
graph_random_users = "/home/luciano/Documentos/Github/complex-networks/resources/data/graph_randon_users_50.csv"
subgraph_initial_users = "/home/luciano/Documentos/Github/complex-networks/resources/data/subgraph_initial_users.csv"
subgraph_random_users = "/home/luciano/Documentos/Github/complex-networks/resources/data/subgraph_random_users.csv"